### ============================
### Get all todos
### ============================
GET http://localhost:3000/todo-list


### ============================
### Create a new todo
### ============================
POST http://localhost:3000/todo-list
Content-Type: application/json

{
  "title": "Learn NestJS architecture properly"
}


### ============================
### Create another todo
### ============================
POST http://localhost:3000/todo-list
Content-Type: application/json

{
  "title": "Refactor JSON DB into repository pattern"
}


### ============================
### Toggle a todo (mark completed)
### Replace <TODO_ID> with real id
### ============================
PATCH http://localhost:3000/todo-list/<TODO_ID>/toggle


### ============================
### Delete a todo
### Replace <TODO_ID> with real id
### ============================
DELETE http://localhost:3000/todo-list/<TODO_ID>
